M48
; DRILL file {KiCad 8.0.3-8.0.3-0~ubuntu20.04.1} date 2024-07-19T14:21:35-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-07-19T14:21:35-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3-8.0.3-0~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X122.945Y-149.5
X178.555Y-149.5
M30
